server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3309/first?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
